### ISSUE TITLE
want the documentation for if clause 

### ISSUE THREAD

**Issue by kattakavya** [224-1/psilib-html5-theremin#11]
please explain the code below
(if (= 0 (:status @inst-state))  
  (do (println "Yet To Start")
      (. osc start 0)                
      (swap! inst-state update-in [:status] inc))
  (. context resume))

what is use of creating gain context ? will max,min gain will all come together?

**Comment by azureus89** [comment]
Will address this after baishakhi attempts #10

**Comment by sahabaishakhi** [comment]
This issue has been addressed and explained over the call by me.

**Comment by sahabaishakhi** [comment]
opening this again as I just read with reference to another issue that confirmation for understanding the code is needed.
