### ISSUE TITLE
Docs needed: audio context

### ISSUE THREAD

**Issue by azureus89** [224-1/psilib-html5-theremin#14]

**Comment by sahabaishakhi** [comment]
audio context is used to handle audio operations through web audio API. the AudioContext is a web audio API interface used to represent an audio processing graph which hooks up different audio nodes to perform various audio operations. `AudioContext()` which is a syntax written in javascript creates and returns a new AudioContext object. the javscript code for creating a new audio context object is `var context = new AudioContext()` whose clojurescript equivalent is `(defonce context (js/window.AudioContext.))` . we create different sources inside the context such as the oscillator, perform operations on them and connect them to the destination.

**Comment by kattakavya** [comment]
An  **audiocontext**  is used for managing and playing all sounds. It  produces a sound using the **Web Audio API**, create one or more sound sources and connect them to the sound destination provided by the audiocontext  instance.
	Generally audio-context controls the creation of the nodes it contains and the execution of the audio processing and decoding for this we are creating the audio-context object which is written as (defonce context (js/window.AudioContext.)),here window is global variable repensting the **window** in which java script is running.
