### ISSUE TITLE
Docs needed: what is the purpose of status in the data model?

### ISSUE THREAD

**Issue by azureus89** [224-1/psilib-html5-theremin#18]

**Comment by sahabaishakhi** [comment]
the status has either the value 0 or 1 which indicates whether the sound has been generated atleast once. if it's 0, it means that the oscillator is yet to generate any sound which leads to a message conveying the same followed by an eventual oscillator sound being generated and the status being increased to 1. once the status is 1, the resume method is used which gets executed to resume the progression of the time in a previously suspended session, which in this case is the sound already being generated via the oscillator

**Comment by ParikshithMohan** [comment]
(defn start-playing []
  (if (= 0 (:status @inst-state))
    (. osc start)))

:status here in my code is just to satisfy the if condition. So when :status is 0 and I click the START button, the condition is satisfied and sound starts playing. Now to stop the sound I have done this: 
:onclick #(. osc stop). I did not use :status to stop the sound when the STOP button is pressed.

**Comment by kattakavya** [comment]
**Status** is taking the binary values of  '0' and '1' , which sets the  audio to start /stop.If the status  value corresponds to zero then first sample-frame in the first block processed by the graph means yet to start the audio and  uniform increments to '1' ,when the status is '1' then the resume() is evoked, it is  progression of current time which has been suspended from the previous session.Resume method is the  time in seconds of the sample frame which immediately follows the last sample-frame in the block of audio most recently processed by the context’s rendering graph. So method is written as (. Context resume)

**Comment by azureus89** [comment]
status is used to detect whether the audio context has been turned on or not. It avoids trying to start the audio context multiple times when the page refreshes. If already on, it attempts to resume instead if required.
