### ISSUE TITLE
Docs needed: what is connect? what is .-destination? Explain wiring

### ISSUE THREAD

**Issue by azureus89** [224-1/psilib-html5-theremin#19]

**Comment by sahabaishakhi** [comment]
the `connect()` method is used to connect different audio nodes to let the sound be passed for further audio processing or to the output. in js the syntax is `osc.connect(amp)` and the cljs way of writing it is `(. osc connect amp)`. we do this step to be able to modify the amplitude of the sine wave generated via the oscillator by multiplying the game parameter to it in the gain node to obtain the desired amplification. 
the resulting sound need to reach the AudioDestinationNode of the audio context which is done by connecting the GainNode to it. the js code for it is `amp.connect(context.destination)` which can be written in cljs as `(. amp connect (.-destination context)))`. -destination is a property of audio context object and essentially an audio node

**Comment by kattakavya** [comment]
**Node**  is a point of intersection or connection where all devices are accessible through the network.
Each node can have inputs and may or may not have  outputs and for destination node has one input and no outputs. The destination is  parameter of  audio-node  that has been created using  context object.
And  the connect() method is used to connect an output of an  audio-node to an input of an audionode.Using connect method here we are connecting two parameters amplitude and oscillator which is written as (.osc connect amp) oscillator is used to   produce sounds/beats and amplitude controls the volume . Here the destination  is connecting to the context object, which is written as 
 (. amp connect (.-destination context)
