### ISSUE TITLE
Attention needed: List of files to be .gitignored?

### ISSUE THREAD

**Issue by ParikshithMohan** [224-1/psilib-html5-theremin#22]
resources/public/cljs-out/dev/figwheel/main/generated/dev_auto_test_runner.js
  resources/public/cljs-out/dev/figwheel/main/generated/dev_auto_test_runner.js.map
  resources/public/cljs-out/dev/psilib/core.cljs
  resources/public/cljs-out/dev/psilib/core.cljs.cache.json
  resources/public/cljs-out/dev/psilib/core.js
  resources/public/cljs-out/dev/psilib/core.js.map
  resources/public/cljs-out/dev/psilib/core_test.js.map
  resources/public/cljs-out/dev/psilib/test_runner.js.map

These are the files that are always unstaged. Out of these I only stage core.cljs in src folder. core.cljs only appears when i change something in the core file. Should i gitignore the other files?

**Comment by azureus89** [comment]
you have to add the whole folder resources/public/cljs-out/ to .gitignore ... but i will address this along with one more thing you have to do so that it works retrospectively in #12 , so im closing this .. we will use that issue for this discussion
