### ISSUE TITLE
Starting the oscillator

### ISSUE THREAD

**Issue by sahabaishakhi** [224-1/psilib-html5-theremin#4]
code block commented as 'Start Oscillator' above wiring. Button is required to run this code block.

**Comment by sahabaishakhi** [comment]
Wiring block required as well to generate audio, hence should be implemented through the button

**Comment by azureus89** [comment]
I dont understand what youre saying?

**Comment by sahabaishakhi** [comment]
I am trying to include the code under 'Start Oscillator' and 'Wiring' inside the function for button implementation

**Comment by azureus89** [comment]
Thats not the most efficient approach. I think you've not understood what that section of the code does. It can work, and probably will, but its the wrong way to do it, you are over-solving it.

**Comment by sahabaishakhi** [comment]
I have implemented a button via the hiccup code. do I need to implement a stop button as well?

**Comment by azureus89** [comment]
Up to you but would be good .. raise a new issue for stop and do it .. but first let me check this and merge it .. need to.close.one issue at least
